### ISSUE TITLE
Can't find 'libsnowcrash.so' when trying to require gem on RedHat 6

### ISSUE THREAD

**Issue by tobiashm** [apiaryio/redsnow#51]
The gem installs just fine, but when trying to require it, it fails with a message about 'libsnowcrash.so' not being found.

```
$ gem install redsnow
...
Fetching: redsnow-0.3.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed redsnow-0.3.4
...
$ irb
2.1.5 :001 > require "redsnow"
LoadError: Could not open library '/.../ruby-2.1.5/gems/redsnow-0.3.4/ext/snowcrash/build/out/Release/lib.target/libsnowcrash.so': /.../ruby-2.1.5/gems/redsnow-0.3.4/ext/snowcrash/build/out/Release/lib.target/libsnowcrash.so: cannot open shared object file: No such file or directory
	from /.../ruby-2.1.5/gems/ffi-1.9.6/lib/ffi/library.rb:133:in `block in ffi_lib'
	from /.../ruby-2.1.5/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `map'
	from /.../ruby-2.1.5/gems/ffi-1.9.6/lib/ffi/library.rb:100:in `ffi_lib'
	from /.../ruby-2.1.5/gems/redsnow-0.3.4/lib/redsnow/binding.rb:12:in `<module:Binding>'
	from /.../ruby-2.1.5/gems/redsnow-0.3.4/lib/redsnow/binding.rb:7:in `<module:RedSnow>'
	from /.../ruby-2.1.5/gems/redsnow-0.3.4/lib/redsnow/binding.rb:3:in `<top (required)>'
	from /.../ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /.../ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /.../ruby-2.1.5/gems/redsnow-0.3.4/lib/redsnow.rb:2:in `<top (required)>'
```

I've seen a couple of issues about snowcrash not building correctly in some situations, but I don't have the knowledge to determine if this problem is related.

**Comment by tobiashm** [comment]
Additional info: I tried to start up a minimal RHEL6 installation using Docker, and only installing rvm (with dependencies), Ruby 2.1.5, and then installing the redsnow gem. This worked fine. The `libsnowcrash.so` file was now created correctly.

So apparently it's a problem with building the snowcrash extension in some situations.

**Comment by tobiashm** [comment]
Some output from running `gem install -V --debug redsnow` on the server where it fails:
```
Path to library /.../ruby-2.1.5/gems/redsnow-0.3.4/ext/snowcrash/build/out/Release/lib.target/libsnowcrash.so
Compiling extension...
Traceback (most recent call last):
  File "tools/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
AttributeError: 'module' object has no attribute 'script_main'
Makefile:358: test-libsnowcrash.target.mk: No such file or directory
make[1]: *** No rule to make target `test-libsnowcrash.target.mk'.  Stop.
make: *** [libsnowcrash] Error 2
Compiling done.
```

**Comment by zdne** [comment]
@pksunkara can you please look into this?

**Comment by tobiashm** [comment]
@zdne @pksunkara thanks.
I've found out that it's a "gyp" package installed on our RedHat servers (from the EPEL repository) that's incompatible with the build script for snowcrash. Will also report to the apiaryio/snowcrash project, but I think it's a problem that the redsnow gem installs OK even though the build of snowcrash fails.

**Comment by pksunkara** [comment]
Hello @tobiashm `gyp` depends on python2.6. Also, please go through this [comment](https://github.com/TooTallNate/node-gyp/issues/363#issuecomment-30575831) once.

**Comment by tobiashm** [comment]
The servers have only Python version 2.6.6 installed.

Installing the redsnow gem in version 0.3.7 works OK now, but the new version 0.4.0 builds fine, but fails when trying to use the gem;

```ruby
require "redsnow"
# LoadError: Could not open library '/home/me/.rvm/gems/ruby-2.2.1/gems/redsnow-0.4.0/ext/drafter/build/out/Release/lib.target/libdrafter.so': /home/me/.rvm/gems/ruby-2.2.1/gems/redsnow-0.4.0/ext/drafter/build/out/Release/lib.target/libdrafter.so: cannot open shared object file: No such file or directory
```

Output from running `gem install -V --debug redsnow`:
```
[...]
Building native extensions.  This could take a while...
Exception `Errno::ENOENT' at /home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1450 - No such file or directory @ unlink_internal - /home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.4.0/gem.build_complete
/home/me/.rvm/rubies/ruby-2.2.1/bin/ruby -rubygems /home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=/home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.4.0 RUBYLIBDIR=/home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.4.0
Path to library /home/me/.rvm/gems/ruby-2.2.1/gems/redsnow-0.4.0/ext/drafter/build/out/Release/lib.target/libdrafter.so
Compiling extension...
Traceback (most recent call last):
  File "./configure", line 11, in <module>
    if sys.version_info.major != 2:
AttributeError: 'tuple' object has no attribute 'major'
Compiling done.

Exception `Errno::EEXIST' at /home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252 - File exists @ dir_s_mkdir - /home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.4.0
Exception `Errno::ENOENT' at /home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1153 - No such file or directory @ utime_internal - /home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.4.0/gem.build_complete
Successfully installed redsnow-0.4.0
```

The same with `-v='0.3.7'` also contains a lot of “errors”, but apparently compiles OK:
```
Building native extensions.  This could take a while...
Exception `Errno::ENOENT' at /home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1450 - No such file or directory @ unlink_internal - /home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.3.7/gem.build_complete
/home/me/.rvm/rubies/ruby-2.2.1/bin/ruby -rubygems /home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=/home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.3.7 RUBYLIBDIR=/home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.3.7
Path to library /home/me/.rvm/gems/ruby-2.2.1/gems/redsnow-0.3.7/ext/snowcrash/build/out/Release/lib.target/libsnowcrash.so
Compiling extension...
g++: out/Release/obj.target/test-libsnowcrash/test/test-ActionParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-AssetParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-Blueprint.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-BlueprintParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-HeadersParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-Indentation.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-ParameterParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-ParametersParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-PayloadParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-RegexMatch.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-ResourceParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-ResourceGroupParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-SectionParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-SymbolIdentifier.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-SymbolTable.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-UriTemplateParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-ValuesParser.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-Warnings.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-csnowcrash.o: No such file or directory
g++: out/Release/obj.target/test-libsnowcrash/test/test-snowcrash.o: No such file or directory
make[1]: *** [out/Release/test-libsnowcrash] Error 1
make: *** [test-libsnowcrash] Error 2
Compiling done.

Exception `Errno::EEXIST' at /home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:252 - File exists @ dir_s_mkdir - /home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.3.7
Exception `Errno::ENOENT' at /home/me/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1153 - No such file or directory @ utime_internal - /home/me/.rvm/gems/ruby-2.2.1/extensions/x86_64-linux/2.2.0/redsnow-0.3.7/gem.build_complete
```

**Comment by tobiashm** [comment]
Looks like the `sys.version_info` object in Python is in another format than the installer expects.
```
$ python
Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.version_info.major
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'major'
>>> sys.version_info
(2, 6, 6, 'final', 0)
```

I'm not proficient in Python, but I hope you might be able to get something out of this :-)

**Comment by zdne** [comment]
Thanks @tobiashm !

 @kylef any clues ? Isn't this related to the changes we've made?

**Comment by kylef** [comment]
@zdne Yes, looks like Python 2.6 doesn't use Python's named tuple for the system version like it does in version 2.7 onwards.

The following pull requests add support for Python 2.6:

- https://github.com/apiaryio/drafter/pull/30
- https://github.com/apiaryio/snowcrash/pull/321

**Comment by pksunkara** [comment]
Merged the related pull requests. Need to update drafter in redsnow and release 0.4.1

**Comment by tobiashm** [comment]
Cool \o/
Thanks for the great products

**Comment by pksunkara** [comment]
0.4.1 released. It should solve this issue.

**Comment by tobiashm** [comment]
Confirmed that 0.4.1 builds on all machines here.

It still puts out some error messages during compilation, when building with `gem install -V --debug redsnow` – but the gem works, so apparently it isn't significant errors ;-)

Here's the part with error messages:
```
Compiling extension...
../src/config.cc:11:21: error: cmdline.h: No such file or directory
../src/config.cc:27: error: variable or field 'PrepareCommanLineParser' declared void
../src/config.cc:27: error: 'cmdline' has not been declared
../src/config.cc:27: error: 'parser' was not declared in this scope
../src/config.cc:48: error: ISO C++ forbids declaration of 'cmdline' with no type
../src/config.cc:48: error: expected ',' or '...' before '::' token
../src/config.cc: In function 'void ValidateParsedCommandLine(int)':
../src/config.cc:50: error: 'parser' was not declared in this scope
../src/config.cc:51: error: 'cerr' is not a member of 'std'
../src/config.cc:51: error: 'endl' is not a member of 'std'
../src/config.cc:52: error: 'EXIT_FAILURE' was not declared in this scope
../src/config.cc:52: error: 'exit' was not declared in this scope
../src/config.cc:55: error: 'parser' was not declared in this scope
../src/config.cc:56: error: 'cout' is not a member of 'std'
../src/config.cc:56: error: 'endl' is not a member of 'std'
../src/config.cc:57: error: 'EXIT_SUCCESS' was not declared in this scope
../src/config.cc:57: error: 'exit' was not declared in this scope
../src/config.cc: In function 'void ParseCommadLineOptions(int, const char**, Config&)':
../src/config.cc:64: error: 'cmdline' has not been declared
../src/config.cc:64: error: expected ';' before 'parser'
../src/config.cc:65: error: 'parser' was not declared in this scope
../src/config.cc:65: error: 'PrepareCommanLineParser' was not declared in this scope
../src/config.cc:77: error: expected primary-expression before '>' token
../src/config.cc:78: error: expected primary-expression before '>' token
../src/config.cc:79: error: expected primary-expression before '>' token
make[1]: *** [out/Release/obj.target/drafter/src/config.o] Error 1
make: *** [drafter] Error 2
Compiling done.
```

**Comment by zdne** [comment]
@tobiashm Interesting. That library (cmdline) is used for unit tests of C++ parser so it shouldn't™ have any impact on the gem itself. But definitely something we may want to look into.
