### ISSUE TITLE
0.3.6 libsnowcrash.dylib Image not found

### ISSUE THREAD

**Issue by jesperronn** [apiaryio/redsnow#58]
Version 0.3.6, I am able to successfully install (without errors). But when I run, I get the following error:

Failure on run:

```
$ bundle exec rake
rake aborted!
LoadError: Could not open library '/Users/jesper/.rvm/gems/ruby-2.1.5/gems/redsnow-0.3.6/ext/snowcrash/build/out/Release/libsnowcrash.dylib': dlopen(/Users/jesper/.rvm/gems/ruby-2.1.5/gems/redsnow-0.3.6/ext/snowcrash/build/out/Release/libsnowcrash.dylib, 5): image not found
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/ffi-1.9.8/lib/ffi/library.rb:133:in `block in ffi_lib'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/ffi-1.9.8/lib/ffi/library.rb:100:in `map'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/ffi-1.9.8/lib/ffi/library.rb:100:in `ffi_lib'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/redsnow-0.3.6/lib/redsnow/binding.rb:12:in `<module:Binding>'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/redsnow-0.3.6/lib/redsnow/binding.rb:7:in `<module:RedSnow>'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/redsnow-0.3.6/lib/redsnow/binding.rb:3:in `<top (required)>'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/Users/jesper/.rvm/gems/ruby-2.1.5/gems/redsnow-0.3.6/lib/redsnow.rb:2:in `<top (required)>'
/Users/jesper/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `require'
/Users/jesper/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/jesper/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `each'
/Users/jesper/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:72:in `block in require'
/Users/jesper/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `each'
/Users/jesper/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/runtime.rb:61:in `require'
/Users/jesper/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler.rb:133:in `require'
/Users/jesper/src/my_project/config/application.rb:8:in `<top (required)>'
/Users/jesper/src/my_project/Rakefile:4:in `require'
/Users/jesper/src/my_project/Rakefile:4:in `<top (required)>'
/Users/jesper/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/Users/jesper/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

Installation goes well:
```
$ bundle
Fetching source index from https://rubygems.org/
bundle exec rake
Using rake 10.4.2
Using ZenTest 4.11.0
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.5.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.6
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.1
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.1
Using globalid 0.3.3
Using activejob 4.2.1
Using mime-types 2.4.3
Using mail 2.6.3
Using actionmailer 4.2.1
Using activemodel 4.2.1
Using arel 6.0.0
Using activerecord 4.2.1
Using addressable 2.3.7
Using ast 2.0.0
Using parser 2.2.0.3
Using astrolabe 1.3.0
Using autotest-rails 4.2.1
Using debug_inspector 0.0.2
Using binding_of_caller 0.7.2
Using thor 0.19.1
Using railties 4.2.1
Using bootstrap-typeahead-rails 0.10.5.1
Using fastercsv 1.5.5
Using tilt 1.4.1
Using haml 4.0.6
Using highline 1.6.21
Using multi_json 1.11.0
Using sexp_processor 4.5.0
Using ruby_parser 3.6.5
Using ruby2ruby 2.1.3
Using sass 3.4.13
Using terminal-table 1.4.5
Using brakeman 3.0.2
Using columnize 0.9.0
Using byebug 4.0.3
Using callsite 0.0.11
Using net-ssh 2.9.2
Using net-scp 1.2.1
Using net-sftp 2.1.2
Using net-ssh-gateway 1.2.0
Using capistrano 2.15.5
Using capistrano_colors 0.5.5
Using xpath 2.0.0
Using capybara 2.4.4
Using chunky_png 1.3.4
Using ci_reporter 2.0.0
Using ci_reporter_minitest 1.0.0
Using cliver 0.3.2
Using docile 1.1.5
Using simplecov-html 0.9.0
Using simplecov 0.9.2
Using codeclimate-test-reporter 0.4.7
Using coderay 1.1.0
Using colorize 0.7.5
Using commonjs 0.2.7
Using safe_yaml 1.0.4
Using crack 0.4.2
Using daemons 1.1.9
Using dotenv 2.0.0
Using dotenv-rails 2.0.0
Using thread 0.1.5
Using easy_translate 0.5.0
Using eventmachine 1.0.7
Using execjs 2.4.0
Using ffi 1.9.8
Using get_process_mem 0.2.0
Using gli 2.12.3
Using hike 1.2.3
Using multi_xml 0.5.5
Using httparty 0.13.3
Using i18n-js 2.1.2
Using slop 3.6.0
Using tins 1.3.5
Using term-ansicolor 1.3.0
Using i18n-tasks 0.7.13
Using jbuilder 2.2.12
Using jquery-rails 4.0.3
Using sprockets 2.12.3
Using sprockets-rails 2.2.4
Using js-routes 1.0.0
Using bundler 1.7.6
Using rails 4.2.1
Using ruby-openid 2.7.0
Using rvm-capistrano 1.5.6
Using less 2.5.1
Using less-rails 2.5.0
Using less-rails-bootstrap 3.2.0
Using sass-rails 5.0.1
Using kgio 2.9.3
Using libv8 3.16.14.7
Using rack-contrib 1.2.0
Using meta_request 0.3.4
Using method_source 0.8.2
Using minitest-capybara 0.7.1
Using minitest-metadata 0.5.3
Using minitest-rails 2.1.1
Using minitest-rails-capybara 2.1.1
Using rmultimarkdown 4.7.0.1
Using mono_logger 1.1.0
Using paper_trail 4.0.0.beta2
Using pg 0.18.1
Using websocket-extensions 0.1.2
Using websocket-driver 0.5.3
Using poltergeist 1.6.0
Using powerpack 0.1.0
Using pry 0.10.1
Using pry-byebug 3.1.0
Using pry-rails 0.3.3
Using pundit 0.3.0
Using rack-protection 1.5.3
Using rack-reverse-proxy 0.4.4
Using rails-erb-lint 1.1.4
Using rails-observers 0.1.2
Using rainbow 2.0.0
Using raindrops 0.13.0
Using redis 3.2.1
Using redis-store 1.1.4
Using redis-rack 1.5.0
Using redis-actionpack 4.0.0
Using redis-activesupport 4.0.0
Using redis-namespace 1.5.1
Using redis-rails 4.0.0
Using yard 0.8.7.6
Installing redsnow 0.3.6
Using ref 1.0.5
Using responders 2.1.0
Using sinatra 1.4.5
Using vegas 0.1.11
Using resque 1.25.2
Using ruby-progressbar 1.7.1
Using rubocop 0.29.1
Using rubocop-checkstyle_formatter 0.1.1
Using ruby-graphviz 1.2.1
Using sass-extras 1.0.2
Using sqlite3 1.3.10
Using state_machines 0.2.2
Using state_machines-activemodel 0.1.2
Using state_machines-activerecord 0.2.0
Using therubyracer 0.12.1
Using thin 1.6.3
Using uglifier 2.7.1
Using unicorn 4.8.3
Using unicorn-worker-killer 0.4.3
Using web-console 2.1.2
Using webmock 1.20.4
Using will_paginate 3.0.7
Using will_paginate-bootstrap 1.0.1
Using yaml_db 0.2.3 from git://github.com/jetthoughts/yaml_db.git (at master)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

```

**Comment by jesperronn** [comment]
This could be related to the updated version from #57

**Comment by pksunkara** [comment]
@jesperronn Could you make sure your python version is 2.6?

This is the error output I got when installing redsnow

```
ath to library /usr/local/lib/rvm/gems/ruby-2.0.0-p598/gems/redsnow-0.3.6/ext/snowcrash/build/out/Release/libsnowcrash.dylib
Compiling extension...
In file included from ../ext/markdown-parser/src/MarkdownParser.cc:11:
../ext/markdown-parser/src/MarkdownParser.h:14:10: fatal error: 'markdown.h' file not found
#include "markdown.h"
         ^
1 error generated.
make[1]: *** [out/Release/obj.target/libmarkdownparser/ext/markdown-parser/src/MarkdownParser.o] Error 1
make: *** [libsnowcrash] Error 2
Compiling done.
```

**Comment by jesperronn** [comment]
@pksunkara pretty sure I use python 2.7 and 3 (installed via homebrew)

```
[16:02:59] $ which -a python
/usr/local/bin/python
/usr/bin/python


[16:03:03] $ python --version
Python 2.7.9


[16:03:08] $ brew info python
python: stable 2.7.9 (bottled), HEAD
https://www.python.org
/usr/local/Cellar/python/2.7.9 (4961 files,  80M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/python.rb
==> Dependencies
Build: pkg-config ✔
Required: openssl ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔
==> Options
--universal
	Build a universal binary
--with-brewed-tk
	Use Homebrew's Tk (has optional Cocoa and threads support)
--with-poll
	Enable select.poll, which is not fully implemented on OS X (http://bugs.python.org/issue5154)
--with-quicktest
	Run `make quicktest` after the build (for devs; may fail)
--without-gdbm
	Build without gdbm support
--without-readline
	Build without readline support
--without-sqlite
	Build without sqlite support
--HEAD
	Install HEAD version
==> Caveats
Pip and setuptools have been installed. To update them
  pip install --upgrade pip setuptools

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

.app bundles were installed.
Run `brew linkapps python` to symlink these to /Applications.
```

**Comment by pksunkara** [comment]
Snowcrash doesn't build without python 2.6. Could you try it using python 2.6?

**Comment by jesperronn** [comment]
can you provide an example from command line if I install Python 2.6 (but prefer not to uninstall more recent versions).

example `gem install redsnow XXXXX`

**Comment by abtris** [comment]
I removed 0.3.6 from rubygems. I think that was corrupted gem. I pushed new versions 0.3.7, please can you try.

**Comment by pksunkara** [comment]
Working for me.

**Comment by jesperronn** [comment]
0.3.7 working for me. (did not have to use python 2.6 as suggested above). Thanks @abtris and @pksunkara for your fast first-aid :+1:
